version: '3.9'

services:
  wol-app:
    build: .
    restart: unless-stopped
    env_file: .env
    network_mode: host  # damit WOL über Broadcast funktioniert
    cap_drop:
      - ALL              # Alle Berechtigungen entfernen
    cap_add:
      - NET_RAW          # Nur zum Senden von Magic Packets
    read_only: true      # Container-Dateisystem schreibgeschützt
    tmpfs:
      - /tmp             # Nur temporärer Speicher erlaubt
