version: '3.9'

services:
  wol-app:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    network_mode: host  # wichtig, damit das Magic Packet per Broadcast rausgeht
    environment:
      - PYTHONUNBUFFERED=1